services:
  user-db:
    image: postgres:16
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    image: node:22-alpine
    container_name: user-service
    working_dir: /app
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@user-db:5432/users_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: users_db
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - user_service_node_modules:/app/node_modules
    command: >
      sh -c "
      npm ci &&
      npx prisma generate &&
      npx prisma db push &&
      npm run start:dev
      "

volumes:
  user_db_data:
  user_service_node_modules: